<form id="addActivity">
    <div class="form-group row">
        <label for="customer_id" class="col-sm-2 col-form-label">org</label>
        <div class="col-sm-10">
            <select class="form-control custom-select" id="selectCustomers" name="customer_id" autofocus required>
                <option value="" selected disabled hidden>Choose here</option>
                <!--
                <option class="my-select-option-customers" value=":N">
                    :N|:NAME
                </option>
                -->
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
    </div>

    <div class="form-group row">
        <label for="description" class="col-sm-2 col-form-label">description</label>
        <div class="col-sm-10">
            <textarea class="form-control" id="description" name="description" rows="10"></textarea>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-10">
        </div>
        <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
            <button type="button" class="btn btn-danger" id="btnCancel">cancel</button>
            <button type="reset" class="btn btn-primary" id="btnReset">reset</button>
            <button type="submit" class="btn btn-success" id="btnSubmit">ok</button>
        </button>
    </div>
</form>
