<?php
$config = \corg\Config::get('site');

header('Content-Type: text/html; charset=UTF-8');
?>

<!DOCTYPE html>
<html lang="eng">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title><?= $config['title'] ?></title>
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/css/custom.css">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand bg-dark navbar-dark fixed-top">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/"><?= $config['title'] ?></a>
                </div>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav mr-auto">
                        <li><a class="nav-link" href="/customer/list">Customers</a></li>
                        <li><a class="nav-link" href="/activity/list">Activities</a></li>
                        <li><a class="nav-link" href="/files/list">Files</a></li>
                    </ul>

                    <ul class="navbar-nav navbar-right">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <?= $_SESSION['employee_nickname'] ?? 'Employee' ?>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="/auth/logout">Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <main role="main" class="container-fluid">
            <?php $this->content(); ?>
        </main>
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/custom.js"></script>
    </body>
</html>

