<?php
$menu = $this->menu;
?>

<form action=<?= $_SERVER['PHP_SELF'] ?> method="POST">
    <div class="form-group">
        <h3>Menu</h3>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Note</th>
                </tr>
                <?php foreach($menu as $m): ?>
                    <tr>
                        <td><?= htmlspecialchars($m['id']) ?></td>
                        <td><?= htmlspecialchars($m['name']) ?></td>
                        <td><?= htmlspecialchars($m['price']) ?></td>
                        <td><?= htmlspecialchars($m['note']) ?></td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block btn-md" name="action" value="ok">ok</button>
    </div>
</form>

