<?php
$tables = $this->tables;
$orders = $this->orders;
$all_checked = $this->all_checked;
$all_checked2 = $this->all_checked2;
$error_msg = $this->error_msg;
?>

<?php foreach($error_msg as $e): ?>
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= htmlspecialchars($e) ?>
    </div>
<?php endforeach ?>

<div class="row">

<div class="col-md-6">
<form action=<?= $_SERVER['PHP_SELF'] ?> method="POST">
    <div class="form-group">
        <h2>Filter Table</h2>
        <select class="form-control" name="table" autofocus>
            <option value="-1">all</option>
            <?php foreach($tables as $k => $v): ?>
                <?php if ($_SESSION['selected_table'] == $k): ?>
                    <option selected value=<?= htmlspecialchars($k) ?>><?= htmlspecialchars($v) ?></option>
                <?php else: ?>
                    <option value=<?= htmlspecialchars($k) ?>><?= htmlspecialchars($v) ?></option>
                <?php endif ?>
            <?php endforeach ?>
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block btn-md" name="action" value="filter_ok">filter</button>
    </div>

    <div class="form-group">
        <h3>Mark as paid</h3>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>Add</th>
                    <th>ID</th>
                    <th>Table</th>
                    <th>Name</th>
                    <th>Price</th>
                </tr>
                <?php foreach($orders as $k => $v): ?>
                    <?php if ($_SESSION['selected_table'] == -1 || $_SESSION['selected_table'] == $v['ttable_id']): ?>
                        <tr>
                            <td>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="checked[]" value="<?= htmlspecialchars($k) ?>" <?= $all_checked ?> >
                                </div>
                            </td>
                            <td><?= htmlspecialchars($k) ?></td>
                            <td><?= htmlspecialchars($v['ttable_num']) ?></td>
                            <td><?= htmlspecialchars($v['name']) ?></td>
                            <td><?= htmlspecialchars($v['price']) ?></td>
                        </tr>
                    <?php endif ?>
                <?php endforeach ?>
            </table>
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-danger btn-block btn-md" name="action">cancel</button></td>
        <button type="submit" class="btn btn-primary btn-block btn-md" name="action" value="set_all_unchecked">unmark all</button>
        <button type="submit" class="btn btn-primary btn-block btn-md" name="action" value="set_all_checked">mark all</button>
        <button type="submit" class="btn btn-success btn-block btn-md" name="action" value="add">add</button>
    </div>
</form>
</div>

<div class="col-md-6">
<form action=<?= $_SERVER['PHP_SELF'] ?> method="POST">
    <div class="form-group">
        <h2>Filter Table</h2>
        <select class="form-control" name="table2" autofocus>
            <option value="-1">all</option>
            <?php foreach($tables as $k => $v): ?>
                <?php if ($_SESSION['selected_table2'] == $k): ?>
                    <option selected value=<?= htmlspecialchars($k) ?>><?= htmlspecialchars($v) ?></option>
                <?php else: ?>
                    <option value=<?= htmlspecialchars($k) ?>><?= htmlspecialchars($v) ?></option>
                <?php endif ?>
            <?php endforeach ?>
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block btn-md" name="action" value="filter_ok2">filter</button>
    </div>

    <div class="form-group">
        <h3>Marked Orders</h3>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>Paid</th>
                    <th>ID</th>
                    <th>Table</th>
                    <th>Name</th>
                    <th>Price</th>
                </tr>
                <?php foreach($_SESSION['pay'] as $k => $v): ?>
                    <?php if ($_SESSION['selected_table2'] == -1 || $_SESSION['selected_table2'] == $v['ttable_id']): ?>
                    <tr>
                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="added[]" value="<?= htmlspecialchars($k) ?>" <?= $all_checked2 ?> >
                            </div>
                        </td>
                        <td><?= htmlspecialchars($k) ?></td>
                        <td><?= htmlspecialchars($v['ttable_num']) ?></td>
                        <td><?= htmlspecialchars($v['name']) ?></td>
                        <td><?= htmlspecialchars($v['price']) ?></td>
                    </tr>
                    <?php endif ?>
                <?php endforeach ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="bg-secondary text-white"><?= $_SESSION['sum'] ?></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-danger btn-block btn-md" name="action">cancel</button></td>
        <button type="submit" class="btn btn-primary btn-block btn-md" name="action" value="set_all_unchecked2">unmark all</button>
        <button type="submit" class="btn btn-primary btn-block btn-md" name="action" value="set_all_checked2">mark all</button>
        <button type="submit" class="btn btn-danger btn-block btn-md" name="action" value="remove">remove</button></td>
        <button type="submit" class="btn btn-success btn-block btn-md" name="action" value="receipt">receipt</button>
        <button type="submit" class="btn btn-success btn-block btn-md" name="action" value="mark_ok">submit</button>
    </div>
</form>
</div>

</div>

