<?php
session_name('mark-as-paid');
session_start();

if (empty($_SESSION) || empty($_SESSION['pay']) || empty($_SESSION['sum'])) {
    header('Location: /pay');
    exit;
}
?>

<form action="/pay" method="POST">
    <div class="form-group">
        <h3>Your Receipt</h3>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                </tr>
                <?php foreach($_SESSION['pay'] as $k => $v): ?>
                    <tr>
                        <td><?= htmlspecialchars($v['name']) ?></td>
                        <td><?= htmlspecialchars($v['price']) ?></td>
                    </tr>
                <?php endforeach ?>
                <tr>
                    <td></td>
                    <td class="bg-secondary text-white"><?= $_SESSION['sum'] ?></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block btn-md">ok</button>
    </div>
</form>
