<div class="list-group">
    <h3>Select action</h3>
    <a href="/menu" class="list-group-item list-group-item-success">Print Menu</a>
    <a href="/take" class="list-group-item list-group-item-warning">Take Order</a>
    <a href="/cook" class="list-group-item list-group-item-info">Mark as Servable</a>
    <a href="/serve" class="list-group-item list-group-item-warning">Mark as Served</a>
    <a href="/cancel" class="list-group-item list-group-item-warning">Mark as Cancelled</a>
    <a href="/pay" class="list-group-item list-group-item-warning">Mark as Paid</a>
</div>
