<?php
$customers = &$this->customers;
$customer = &$this->customer;
$activities = &$this->activities;
$id = &$this->id;
$associations = &$this->associations;
$error_msg = &$this->error_msg;
?>

<?php foreach($error_msg as $e): ?>
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= htmlspecialchars($e) ?>
    </div>
<?php endforeach ?>

<div class="row">
    <div class="col-sm-2">
        <nav class="nav nav-pills flex-column">
            <div class="sidebar-header">
                <h3>Customers <span class="badge badge-light"><?= count($customers) ?></span></h3>
            </div>
            <?php foreach($customers as $k => $v): ?>
                <a class="nav-link <?= $k == $id ? 'active' : '' ?>" href="/customer/list/<?= htmlspecialchars($k) ?>">
                    <?= htmlspecialchars($v) ?>
                </a>
            <?php endforeach ?>
        </nav>
    </div>

    <div class="col">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-info-tab" data-toggle="pill" href="#pills-info" role="tab" aria-controls="pills-info" aria-selected="true">Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-associations-tab" data-toggle="pill" href="#pills-associations" role="tab" aria-controls="pills-associations" aria-selected="false">
                    Associations <span class="badge badge-light"><?= count($associations) ?></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-activities-tab" data-toggle="pill" href="#pills-activities" role="tab" aria-controls="pills-activities" aria-selected="false">
                    Activities <span class="badge badge-light"><?= count($activities) ?></span>
                </a>
            </li>
        </ul>

        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane active" id="pills-info" role="tabpanel" aria-labelledby="pills-info-tab">
                <form>
                    <div class="form-group row">
                        <div class="col-9">
                        </div>
                        <div class="btn-group btn-group-sm col-sm-3" role="group" aria-label="actions" >
                            <button type="button" class="btn btn-warning">
                                <a href="/customer/export/<?= $id ?>" style="color:inherit">export</a>
                            </button>
                            <button type="button" class="btn btn-success">
                                <a href="/customer/add" style="color:inherit">new</a>
                            </button>
                            <button type="button" class="btn btn-danger">
                                <a href="/customer/delete/<?= $id ?>" style="color:inherit">delete</a>
                            </button>
                            <button type="button" class="btn btn-primary" disabled>
                            <a href="/customer/edit/<?= $id ?>" style="color:inherit">edit</a>
                            </button>
                        </div>
                    </div>

                    <fieldset class="form-group">
                        <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">meta</legend>
                            <div class="col-sm-10">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-form-label col-sm-2 pt-0">
                            </div>
                            <div class="col-sm-10">
                                <div class="form-group row">
                                    <label for="id" class="col-sm-2 col-form-label">id</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="id" placeholder="<?= htmlspecialchars($customer['id']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="nickname" class="col-sm-2 col-form-label">nickname</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="nickname" placeholder="<?= htmlspecialchars($customer['nickname']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="rev" class="col-sm-2 col-form-label">rev</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="rev" placeholder="<?= htmlspecialchars($customer['rev']) ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset class="form-group">
                        <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">address</legend>
                            <div class="col-sm-10">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-form-label col-sm-2 pt-0">
                            </div>
                            <div class="col-sm-10">
                                <div class="form-group row">
                                    <label for="url" class="col-sm-2 col-form-label">url</label>
                                    <div class="col-sm-10">
                                        <input type="url" readonly class="form-control" id="url" placeholder="<?= htmlspecialchars($customer['url']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="post_office_box" class="col-sm-2 col-form-label">post_office_box</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="post_office_box" placeholder="<?= htmlspecialchars($customer['post_office_box']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="street_address" class="col-sm-2 col-form-label">street_address</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="street_address" placeholder="<?= htmlspecialchars($customer['street_address']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="extended_address" class="col-sm-2 col-form-label">extended_address</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="extended_address" placeholder="<?= htmlspecialchars($customer['extended_address']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="locality" class="col-sm-2 col-form-label">locality</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="locality" placeholder="<?= htmlspecialchars($customer['locality']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="region" class="col-sm-2 col-form-label">region</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="region" placeholder="<?= htmlspecialchars($customer['region']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="postal_code" class="col-sm-2 col-form-label">postal_code</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="postal_code" placeholder="<?= htmlspecialchars($customer['postal_code']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="country_name" class="col-sm-2 col-form-label">country_name</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="country_name" placeholder="<?= htmlspecialchars($customer['country_name']) ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset class="form-group">
                        <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">contact</legend>
                            <div class="col-sm-10">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-form-label col-sm-2 pt-0">
                            </div>
                            <div class="col-sm-10">
                                <div class="form-group row">
                                    <label for="role" class="col-sm-2 col-form-label">role</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="role" placeholder="<?= htmlspecialchars($customer['role']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="family_name" class="col-sm-2 col-form-label">family_name</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="family_name" placeholder="<?= htmlspecialchars($customer['family_name']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="given_name" class="col-sm-2 col-form-label">given_name</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="given_name" placeholder="<?= htmlspecialchars($customer['given_name']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="additional_name" class="col-sm-2 col-form-label">additional_name</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="additional_name" placeholder="<?= htmlspecialchars($customer['additional_name']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="honorific_prefix" class="col-sm-2 col-form-label">honorific_prefix</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="honorific_prefix" placeholder="<?= htmlspecialchars($customer['honorific_prefix']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="honorific_suffix" class="col-sm-2 col-form-label">honorific_suffix</label>
                                    <div class="col-sm-10">
                                        <input type="text" readonly class="form-control" id="honorific_suffix" placeholder="<?= htmlspecialchars($customer['honorific_suffix']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="tel" class="col-sm-2 col-form-label">tel</label>
                                    <div class="col-sm-10">
                                        <input type="tel" readonly class="form-control" id="tel" placeholder="<?= htmlspecialchars($customer['tel']) ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="email" class="col-sm-2 col-form-label">email</label>
                                    <div class="col-sm-10">
                                        <input type="email" readonly class="form-control" id="email" placeholder="<?= htmlspecialchars($customer['email']) ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <div class="form-group row">
                        <div class="col-9">
                        </div>
                        <div class="btn-group btn-group-sm col-sm-3" role="group" aria-label="actions" >
                            <button type="button" class="btn btn-warning">
                                <a href="/customer/export/<?= $id ?>" style="color:inherit">export</a>
                            </button>
                            <button type="button" class="btn btn-success">
                                <a href="/customer/add" style="color:inherit">new</a>
                            </button>
                            <button type="button" class="btn btn-danger">
                                <a href="/customer/delete/<?= $id ?>" style="color:inherit">delete</a>
                            </button>
                            <button type="button" class="btn btn-primary" disabled>
                                <a href="/customer/edit/<?= $id ?> "style="color:inherit">edit</a>
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="tab-pane" id="pills-associations" role="tabpanel" aria-labelledby="pills-associations-tab">
                <div class="row">
                    <div class="col-10">
                    </div>
                    <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                        <button type="button" class="btn btn-success">
                            <a href="/customer/associate/<?= $customer['id'] ?>" style="color:inherit">new</a>
                        </button>
                        <button type="button" class="btn btn-danger">
                            <a href="/customer/dissociate/<?= $customer['id'] ?>" style="color:inherit">delete</a>
                        </button>
                    </div>
                </div>
                <div class="table-responsive table-sm mt-4">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>org</th>
                        </tr>
                        <?php foreach($associations as $k => $v): ?>
                            <tr class="table-row" data-href="/customer/list/<?= htmlspecialchars($k) ?>">
                                <td><?= htmlspecialchars($v) ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div>

            <div class="tab-pane" id="pills-activities" role="tabpanel" aria-labelledby="pills-activities-tab">
                <div class="row">
                    <div class="col-10">
                    </div>
                    <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                        <button type="button" class="btn btn-success">
                        <a href="/activity/add/<?= $customer['id'] ?>" style="color:inherit">new</a>
                        </button>
                    </div>
                </div>
                <div class="table-responsive table-sm mt-4">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>mtime</th>
                            <th>name</th>
                            <th>description</th>
                        </tr>
                        <?php foreach($activities as $k => $v): ?>
                            <tr class="table-row" data-href="/activity/list/<?= htmlspecialchars($k) ?>">
                                <td><?= htmlspecialchars($v['mtime']) ?></td>
                                <td><?= htmlspecialchars($v['name']) ?></td>
                                <td><?= htmlspecialchars($v['description']) ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                <div>
            </div>
        </div>
    </div>
</div>
