<?php
$files = &$this->files;
$file = &$this->file;
$id = &$this->id;
$error_msg = &$this->error_msg;
?>

<?php foreach($error_msg as $e): ?>
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= htmlspecialchars($e) ?>
    </div>
<?php endforeach ?>

<div class="row">
    <div class="col-sm-2">
        <nav class="nav nav-pills flex-column">
            <div class="sidebar-header">
                <h3>Files <span class="badge badge-light"><?= count($files) ?></span></h3>
            </div>
            <?php foreach($files as $v): ?>
                <a class="nav-link <?= $v == $id ? 'active' : '' ?>" href="/files/list/<?= $v ?>">
                    <?= htmlspecialchars($v) ?>
                </a>
            <?php endforeach ?>
        </nav>
    </div>

    <div class="col">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-info-tab" data-toggle="pill" href="#pills-info" role="tab" aria-controls="pills-info" aria-selected="true">Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-references-tab" data-toggle="pill" href="#pills-references" role="tab" aria-controls="pills-references" aria-selected="true">
                    References <span class="badge badge-light"><?= count($file) ?></span>
                </a>
            </li>
        </ul>

        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane active" id="pills-info" role="tabpanel" aria-labelledby="pills-info-tab">
                <form>
                    <div class="form-group row">
                        <div class="col-9">
                        </div>
                        <div class="btn-group btn-group-sm col-sm-3" role="group" aria-label="actions" >
                            <button type="button" class="btn btn-warning">
                                <a href="/files/download/<?= $id ?>" style="color:inherit">download</a>
                            </button>
                            <button type="button" class="btn btn-success">
                                <a href="/files/add" style="color:inherit">new</a>
                            </button>
                            <button type="button" class="btn btn-danger">
                                <a href="/files/delete/<?= $id ?>" style="color:inherit">delete</a>
                            </button>
                            <button type="button" class="btn btn-primary" disabled>
                                <a style="color:inherit">edit</a>
                            </button>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="mtime" class="col-sm-2 col-form-label">mtime</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" name="mtime" placeholder="<?= $file[0]['mtime'] ?? null ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="size" class="col-sm-2 col-form-label">size</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" name="size" placeholder="<?= $file[0]['size'] ?? null ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="mtype" class="col-sm-2 col-form-label">mtype</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" name="mtype" placeholder="<?= $file[0]['mtype'] ?? null ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">name</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" name="name" placeholder="<?= $file[0]['name'] ?? null ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-sm-2 col-form-label">description</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" readonly name="description" rows="10" placeholder="<?= $file[0]['description'] ?? null ?>"></textarea>
                        </div>
                    </div>
                </form>
            </div>

            <div class="tab-pane" id="pills-references" role="tabpanel" aria-labelledby="pills-references-tab">
                <div class="row">
                    <div class="col-10">
                    </div>
                    <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                        <button type="button" class="btn btn-success">
                            <a href="/files/reference/<?= $id ?>" style="color:inherit">new</a>
                        </button>
                        <button type="button" class="btn btn-danger">
                            <a href="/files/dereference/<?= $id ?>" style="color:inherit">delete</a>
                        </button>
                    </div>
                </div>
                <div class="table-responsive table-sm mt-4">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>org</th>
                            <th>activity</th>
                        </tr>
                        <?php foreach($file as $k => $v): ?>
                            <tr class="table-row" data-href="/activity/list/<?= $v['activity_id'] ?>">
                                <td><?= htmlspecialchars($v['org']) ?></td>
                                <td><?= htmlspecialchars($v['activity_name']) ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                <div>
            </div>
        </div>
    </div>
</div>

