<ul class="nav nav-tabs mb-3" id="tab-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="tab-info-tab" data-toggle="tab" href="#tab-info" role="tab" aria-controls="tab-info" aria-selected="true">Info</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab-associations-tab" data-toggle="tab" href="#tab-associations" role="tab" aria-controls="tab-associations" aria-selected="false">
            Associations <span class="badge badge-light" id="associatonsCount">0</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab-activities-tab" data-toggle="tab" href="#tab-activities" role="tab" aria-controls="tab-activities" aria-selected="false">
            Activities <span class="badge badge-light" id="activitiesCount">0</span>
        </a>
    </li>
</ul>

<div class="tab-content" id="tab-tabContent">
    <div class="tab-pane active" id="tab-info" role="tabpanel" aria-labelledby="tab-info-tab">
        <form id="fetchOrg">
            <div class="form-group row">
                <div class="col-9">
                </div>
                <div class="btn-group btn-group-sm col-sm-3" role="group" aria-label="actions" >
                    <button type="button" class="btn btn-warning my-button-customer-export">
                        export
                    </button>
                    <button type="button" class="btn btn-success my-button-customer-add">
                        new
                    </button>
                    <button type="button" class="btn btn-danger my-button-customer-remove">
                        remove
                    </button>
                    <button type="button" class="btn btn-primary my-button-customer-edit">
                        edit
                    </button>
                </div>
            </div>

            <fieldset class="form-group">
                <div class="row">
                    <legend class="col-form-label col-sm-2 pt-0">meta</legend>
                    <div class="col-sm-10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-form-label col-sm-2 pt-0">
                    </div>
                    <div class="col-sm-10">
                        <div class="form-group row">
                            <label for="nickname" class="col-sm-2 col-form-label">employee</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="nickname" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="rev" class="col-sm-2 col-form-label">rev</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="rev" placeholder="">
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset class="form-group">
                <div class="row">
                    <legend class="col-form-label col-sm-2 pt-0">address</legend>
                    <div class="col-sm-10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-form-label col-sm-2 pt-0">
                    </div>
                    <div class="col-sm-10">
                        <div class="form-group row">
                            <label for="url" class="col-sm-2 col-form-label">url</label>
                            <div class="col-sm-10">
                                <input type="url" readonly class="form-control" id="url" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="post_office_box" class="col-sm-2 col-form-label">post_office_box</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="post_office_box" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="street_address" class="col-sm-2 col-form-label">street_address</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="street_address" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="extended_address" class="col-sm-2 col-form-label">extended_address</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="extended_address" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="locality" class="col-sm-2 col-form-label">locality</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="locality" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="region" class="col-sm-2 col-form-label">region</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="region" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="postal_code" class="col-sm-2 col-form-label">postal_code</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="postal_code" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="country_name" class="col-sm-2 col-form-label">country_name</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="country_name" placeholder="">
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset class="form-group">
                <div class="row">
                    <legend class="col-form-label col-sm-2 pt-0">contact</legend>
                    <div class="col-sm-10">
                    </div>
                </div>
                <div class="row">
                    <div class="col-form-label col-sm-2 pt-0">
                    </div>
                    <div class="col-sm-10">
                        <div class="form-group row">
                            <label for="role" class="col-sm-2 col-form-label">role</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="role" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="family_name" class="col-sm-2 col-form-label">family_name</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="family_name" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="given_name" class="col-sm-2 col-form-label">given_name</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="given_name" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="additional_name" class="col-sm-2 col-form-label">additional_name</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="additional_name" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="honorific_prefix" class="col-sm-2 col-form-label">honorific_prefix</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="honorific_prefix" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="honorific_suffix" class="col-sm-2 col-form-label">honorific_suffix</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control" id="honorific_suffix" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="tel" class="col-sm-2 col-form-label">tel</label>
                            <div class="col-sm-10">
                                <input type="tel" readonly class="form-control" id="tel" placeholder="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-sm-2 col-form-label">email</label>
                            <div class="col-sm-10">
                                <input type="email" readonly class="form-control" id="email" placeholder="">
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>

            <div class="form-group row">
                <div class="col-9">
                </div>
                <div class="btn-group btn-group-sm col-sm-3" role="group" aria-label="actions" >
                    <button type="button" class="btn btn-warning my-button-customer-export">
                        export
                    </button>
                    <button type="button" class="btn btn-success my-button-customer-add">
                        new
                    </button>
                    <button type="button" class="btn btn-danger my-button-customer-remove">
                        remove
                    </button>
                    <button type="button" class="btn btn-primary my-button-customer-edit">
                        edit
                    </button>
                </div>
            </div>
        </form>
    </div>

    <div class="tab-pane" id="tab-associations" role="tabpanel" aria-labelledby="tab-associations-tab">
        <div class="row">
            <div class="col-10">
            </div>
            <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                <button type="button" class="btn btn-success my-button-customer-associate">
                    new
                </button>
                <button type="button" class="btn btn-danger my-button-customer-dissociate">
                    remove
                </button>
            </div>
        </div>
        <div class="table-responsive table-sm mt-4">
            <table class="table table-striped table-hover" id="tableAssociations">
                <thead>
                    <tr>
                        <th>org</th>
                    </tr>
                </thead>
                <tbody>
                <!--
                    <tr class="my-table-row-associations" data-id=":N" data-org=":ORG" data-href="/customers/N">
                        <td>:ORG/td>
                    </tr>
                    -->
                </tbody>
            </table>
        </div>
    </div>

    <div class="tab-pane" id="tab-activities" role="tabpanel" aria-labelledby="tab-activities-tab">
        <div class="row">
            <div class="col-10">
            </div>
            <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                <button type="button" class="btn btn-success my-button-activity-add">
                    new
                </button>
            </div>
        </div>
        <div class="table-responsive table-sm mt-4">
            <table class="table table-striped table-hover" id="tableActivities">
                <thead>
                    <tr>
                        <th>mtime</th>
                        <th>name</th>
                        <th>description</th>
                    </tr>
                </thead>
                <tbody>
                    <!--
                    <tr class="my-table-row-activities" data-id=":N" data-href="/activities/N">
                        <td>:MTIME</td>
                        <td>:NAME</td>
                        <td>:DESCRIPTION</td>
                    </tr>
                    -->
                </tbody>
            </table>
        </div>
    </div>
</div>

