<nav class="nav nav-pills flex-column" id="orgNav">
    <div class="sidebar-header">
        <h3>Customers<span class="badge badge-light" id="orgCount">0</span></h3>
    </div>

    <input class="form-control mr-sm-2 mb-2" type="search" id="orgSearch" placeholder="Filter" aria-label="orgSearch">

    <div id="orgNavLinks">
        <!--
        <a class="nav-link my-nav-link" href="/customers/N" data-href="/customers/N" data-id="N" data-org="ORG">
                :N | :ORG
        </a>
        -->
    <div>
</nav>
