<div class="col-sm-4">
    <form id="loginAuth">
        <div class="form-group row">
            <label for="username" class="sr-only" >username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="username" required autofocus>
        </div>

        <div class="form-group row">
            <label for="password" class="sr-only">password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="password" required>
        </div>

        <div class="form-group row">
            <div class="btn-group btn-group-sm" role="group" aria-label="actions" >
                <button type="submit" class="btn btn-primary" id="btnSignIn" disabled>sign in</button>
                <button type="submit" class="btn btn-primary" id="btnRegister">register</button>
                <button type="button" class="btn btn-primary" id="btnLogout" disabled>logout</button>
            </div>
        </div>
    </form>
</div>

<div class="col-sm-3">
</div>
<div class="col-sm-3">
</div>
