<?php
$activities = &$this->activities;
$activity = &$this->activity;
$id = &$this->id;
$files = &$this->files;
$error_msg = &$this->error_msg;
?>

<?php foreach($error_msg as $e): ?>
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= htmlspecialchars($e) ?>
    </div>
<?php endforeach ?>

<div class="row">
    <div class="col-sm-2">
        <nav class="nav nav-pills flex-column">
            <div class="sidebar-header">
                <h3>Activities <span class="badge badge-light"><?= count($activities) ?></span></h3>
            </div>
            <?php foreach($activities as $v): ?>
                <a class="nav-link <?= $v == $id ? 'active' : '' ?>" href="/activity/list/<?= htmlspecialchars($v) ?>">
                    <?= htmlspecialchars($v) ?>
                </a>
            <?php endforeach ?>
        </nav>
    </div>

    <div class="col">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-info-tab" data-toggle="pill" href="#pills-info" role="tab" aria-controls="pills-info" aria-selected="true">Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-files-tab" data-toggle="pill" href="#pills-files" role="tab" aria-controls="pills-files" aria-selected="false">
                    Files <span class="badge badge-light"><?= count($files) ?></span>
                </a>
            </li>
        </ul>

        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane active" id="pills-info" role="tabpanel" aria-labelledby="pills-info-tab">
                <form>
                    <div class="form-group row">
                        <div class="col-10">
                        </div>
                        <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                            <button type="button" class="btn btn-success">
                                <a href="/activity/add" style="color:inherit">new</a>
                            </button>
                            <button type="button" class="btn btn-danger">
                                <a href="/activity/delete/<?= $id ?>" style="color:inherit">delete</a>
                            </button>
                            <button type="button" class="btn btn-primary" disabled>
                                <a style="color:inherit">edit</a>
                            </button>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="nickname" class="col-sm-2 col-form-label">nickname</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" id="nickname" placeholder="<?= htmlspecialchars($activity['nickname']) ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="mtime" class="col-sm-2 col-form-label">mtime</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" id="mtime" placeholder="<?= htmlspecialchars($activity['mtime']) ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="org" class="col-sm-2 col-form-label"><a href="/customer/list/<?= htmlspecialchars($activity['customer_id']) ?>">org</a></label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" id="org" placeholder="<?= htmlspecialchars($activity['org']) ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">name</label>
                        <div class="col-sm-10">
                            <input type="text" readonly class="form-control" id="name" placeholder="<?= htmlspecialchars($activity['name']) ?>">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-sm-2 col-form-label">description</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" readonly id="description" rows="10" placeholder="<?= htmlspecialchars($activity['description']) ?>"></textarea>
                        </div>
                    </div>
                </form>
            </div>


            <div class="tab-pane" id="pills-files" role="tabpanel" aria-labelledby="pills-associations-tab">
                <div class="row">
                    <div class="col-10">
                    </div>
                    <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                        <button type="button" class="btn btn-success">
                            <a href="/files/add/<?= $activity['id'] ?>" style="color:inherit">new</a>
                        </button>
                    </div>
                </div>
                <div class="table-responsive table-sm mt-4">
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>mtime</th>
                            <th>size</th>
                            <th>name</th>
                        </tr>
                        <?php foreach($files as $k => $v): ?>
                            <tr class="table-row" data-href="/files/list/<?= htmlspecialchars($k) ?>">
                                <td><?= htmlspecialchars($v['mtime']) ?></td>
                                <td><?= htmlspecialchars($v['size']) ?></td>
                                <td><?= htmlspecialchars($v['name']) ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
