<div class="row">

    <div class="col-sm-4">
        <h4>Customers <span class="badge badge-light" id="customerCount">0</span></h4>
        <div class="table-responsive table-sm mt-4">
            <table class="table table-striped table-hover" id="tableCustomers">
                <thead>
                    <tr>
                        <th>rev</th>
                        <th>org</th>
                    </tr>
                </thead>
                <tbody>
                    <!--
                    <tr class="my-table-row-customers" data-id=":N" data-href="/customers/N">
                        <td>:REV</td>
                        <td>:ORG</td>
                    </tr>
                    -->
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-sm-4">
        <h4>Activities <span class="badge badge-light" id="activityCount">0</span></h4>
        <div class="table-responsive table-sm mt-4">
            <table class="table table-striped table-hover" id="tableActivities">
                <thead>
                    <tr>
                        <th>mtime</th>
                        <th>org</th>
                        <th>name</th>
                    </tr>
                </thead>
                <tbody>
                    <!--
                    <tr class="my-table-row-activities" data-id=":N" data-href="/activities/N">
                        <td>:MTIME</td>
                        <td>:ORG</td>
                        <td>:NAME</td>
                    </tr>
                    -->
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-sm-4">
        <h4>Files <span class="badge badge-light" id="fileCount">0</span></h4>
        <div class="table-responsive table-sm mt-4">
            <table class="table table-striped table-hover" id="tableFiles">
                <thead>
                    <tr>
                        <th>mtime</th>
                        <th>activity</th>
                        <th>name</th>
                    </tr>
                </thead>
                <tbody>
                    <!--
                    <tr class="my-table-row-files" data-id=":N" data-href="/files/N">
                        <td>:MTIME</td>
                        <td>:ACTIVITY</td>
                        <td>:NAME</td>
                    </tr>
                    -->
                </tbody>
            </table>
        </div>
    </div>

</div>
