<ul class="nav nav-tabs mb-3" id="tab-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="tab-info-tab" data-toggle="tab" href="#tab-info" role="tab" aria-controls="tab-info" aria-selected="true">Info</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab-references-tab" data-toggle="tab" href="#tab-references" role="tab" aria-controls="tab-references" aria-selected="true">
            References <span class="badge badge-light" id="referencesCount">0</span>
        </a>
    </li>
</ul>

<div class="tab-content" id="tab-tabContent">
    <div class="tab-pane active" id="tab-info" role="tabpanel" aria-labelledby="tab-info-tab">
        <form id="fetchFile">
            <div class="form-group row">
                <div class="col-9">
                </div>
                <div class="btn-group btn-group-sm col-sm-3" role="group" aria-label="actions" >
                    <button type="button" class="btn btn-warning my-button-file-download">
                        download
                    </button>
                    <button type="button" class="btn btn-success my-button-file-add">
                        new
                    </button>
                    <button type="button" class="btn btn-danger my-button-file-remove">
                        remove
                    </button>
                </div>
            </div>

            <div class="form-group row">
                <label for="mtime" class="col-sm-2 col-form-label">mtime</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="mtime" placeholder="">
                </div>
            </div>

            <div class="form-group row">
                <label for="size" class="col-sm-2 col-form-label">size</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="size" placeholder="">
                </div>
            </div>

            <div class="form-group row">
                <label for="mtype" class="col-sm-2 col-form-label">mtype</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="mtype" placeholder="">
                </div>
            </div>

            <div class="form-group row">
                <label for="description" class="col-sm-2 col-form-label">description</label>
                <div class="col-sm-10">
                    <textarea class="form-control" readonly id="description" rows="10" placeholder=""></textarea>
                </div>
            </div>
        </form>
    </div>

    <div class="tab-pane" id="tab-references" role="tabpanel" aria-labelledby="tab-references-tab">
        <div class="row">
            <div class="col-10">
            </div>
            <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                <button type="button" class="btn btn-success my-button-reference-reference">
                    new
                </button>
                <button type="button" class="btn btn-danger my-button-reference-dereference">
                    remove
                </button>
            </div>
        </div>
        <div class="table-responsive table-sm mt-4">
            <table class="table table-striped table-hover" id="tableReferences">
                <thead>
                    <tr>
                        <th>org</th>
                        <th>activity</th>
                    </tr>
                </thead>
                <tbody>
                    <!--
                    <tr class="my-table-row-references" data-id=":N" data-href="/activities/N">
                        <td>:ORG</td>
                        <td>:ACTIVITY_NAME</td>
                    </tr>
                    -->
                </tbody>
            </table>
        </div>
    </div>
</div>

