<nav class="nav nav-pills flex-column" id="fileNav">
    <div class="sidebar-header">
        <h3>Files<span class="badge badge-light" id="fileCount">0</span></h3>
    </div>

    <input class="form-control mr-sm-2 mb-2" type="search" id="fileSearch" placeholder="Filter" aria-label="fileSearch">

    <div id="fileNavLinks">
        <!--
        <a class="nav-link my-nav-link" href="/files/N" data-href="/files/N" data-id="N" data-name="FILE">
                :N | :FILE
        </a>
        -->
    <div>
</nav>
