<?php
$config = \bestellando\Config::get('site');

header('Content-Type: text/html; charset=UTF-8');
?><!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
        <title><?= $config['title'] ?></title>
    </head>
    <body>
        <div class='container'>
            <?php $this->content(); ?>
        </div>
    </body>
</html>
