<?php
$error_msg = &$this->error_msg;
$references = &$this->references;
$file_id = &$this->file_id;
$file_name = &$this->file_name;
?>

<?php foreach($error_msg as $e): ?>
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= htmlspecialchars($e) ?>
    </div>
<?php endforeach ?>

<h3>Remove Reference</h3>

<form action="<?= '/files/dereference/' . htmlspecialchars($file_id) ?>" method="POST">
    <div class="form-group row">
        <label for="file_id" class="col-sm-2 col-form-label">file</label>
        <div class="col-sm-10">
            <select class="form-control custom-select" id="file_id" name="file_id" readonly required>
                <option value=<?= htmlspecialchars($file_id) ?>>
                        <?= htmlspecialchars($file_name) ?>
                </option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-2">
        </div>
        <div class="table-responsive table-sm col-sm-10">
            <table class="table table-striped table-hover">
                <tr>
                    <th>
                        <div class="form-check">
                            <label>
                                <input class="form-check-input" type="checkbox" id="checkAll">
                                check
                            </label>
                      </div>
                    <th>activity</th>
                </tr>
                <?php foreach($references as $k => $v): ?>
                    <tr>
                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="ids[]" value="<?= htmlspecialchars($v) ?>">
                            </div>
                        </td>
                        <td>
                            <a href="/activity/list/<?= htmlspecialchars($v) ?>">
                                <?= htmlspecialchars($v) ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-10">
        </div>
        <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
            <button type="button" class="btn btn-danger">
                <a href="/files/list/<?= htmlspecialchars($file_id) ?>" style="color:inherit">cancel</a>
            </button>
            <button type="submit" class="btn btn-success" name="action" value="ok">ok</button>
        </button>
    </div>
</form>


