<?php
$error_msg = &$this->error_msg;
$associations = &$this->associations;
$customer_id_1 = &$this->customer_id_1;
$customer_org_1 = &$this->customer_org_1;
$check_state = &$this->check_state;
?>

<?php foreach($error_msg as $e): ?>
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= htmlspecialchars($e) ?>
    </div>
<?php endforeach ?>

<h3>Remove Associations</h3>

<form action="<?= '/customer/dissociate/' . htmlspecialchars($customer_id_1) ?>" method="POST">
    <div class="form-group row">
        <label for="customer_id_1" class="col-sm-2 col-form-label">customer1</label>
        <div class="col-sm-10">
            <select class="form-control custom-select" id="customer_id_1" name="customer_id_1" readonly required>
                <option value=<?= htmlspecialchars($customer_id_1) ?>>
                        <?= htmlspecialchars($customer_org_1) ?>
                </option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-2">
        </div>
        <div class="table-responsive table-sm col-sm-10">
            <table class="table table-striped table-hover">
                <tr>
                    <th>
                        <div class="form-check">
                            <label>
                                <input class="form-check-input" type="checkbox" id="checkAll">
                                check
                            </label>
                      </div>
                    <th>org</th>
                </tr>
                <?php foreach($associations as $k => $v): ?>
                    <tr>
                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="ids[]" value="<?= htmlspecialchars($k) ?>" <?= $check_state ?>>
                            </div>
                        </td>
                        <td>
                            <a href="/customer/list/<?= htmlspecialchars($k) ?>">
                                <?= htmlspecialchars($v) ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-10">
        </div>
        <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
            <button type="button" class="btn btn-danger">
                <a href="/customer/list/<?= htmlspecialchars($customer_id_1) ?>" style="color:inherit">cancel</a>
            </button>
            <button type="submit" class="btn btn-success" name="action" value="ok">ok</button>
        </button>
    </div>
</form>

