<div class="col" id="mainRightColFetch" style="display: block;">
    <?php
        $this->content('/index/customer/fetch/main.phtml');
    ?>
</div>

<div class="col" id="mainRightColAdd" style="display: none;">
    <?php
        $this->content('/index/customer/add/main.phtml');
    ?>
</div>

<div class="col" id="mainRightColEdit" style="display: none;">
    <?php
        $this->content('/index/customer/edit/main.phtml');
    ?>
</div>
