<div class="col" id="mainLeftColFetch" style="display: block;">
    <?php
        $this->content('/index/customer/fetch/nav.phtml');
    ?>
</div>

<div class="col" id="mainLeftColAdd" style="display: none;">
    <?php
        $this->content('/index/customer/add/nav.phtml');
    ?>
</div>

<div class="col" id="mainLeftColEdit" style="display: none;">
    <?php
        $this->content('/index/customer/edit/nav.phtml');
    ?>
</div>
