<form id="addFile">
    <div class="form-group row">
        <div class="col-2">
            file
        </div>
        <div class="input-group col-sm-10">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="fileUpload" name="uploaded_file" aria-describedby="btnUpload" required autofocus>
                <label class="custom-file-label" for="fileUpload"></label>
            </div>
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary" id="btnUpload" name="action" value="upload">upload</button>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="selectActivities" class="col-sm-2 col-form-label">activity</label>
        <div class="col-sm-10">
            <select class="form-control custom-select" id="selectActivities" name="activity_id">
                <option value="" selected disabled hidden>Choose here</option>
                    <!--
                    <option class="my-select-option-activities" value=":N">
                        :N|:NAME
                    </option>
                    -->
                <option value="1">1|test</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="size" class="col-sm-2 col-form-label">size</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control" id="size" name="size" value="">
        </div>
    </div>

    <div class="form-group row">
        <label for="mtype" class="col-sm-2 col-form-label">mtype</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control" id="mtype" name="mtype" value="">
        </div>
    </div>

    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">name</label>
        <div class="col-sm-10">
            <input type="text" disabled class="form-control" id="name" name="name" value="" required>
        </div>
    </div>

    <div class="form-group row">
        <label for="description" class="col-sm-2 col-form-label">description</label>
        <div class="col-sm-10">
            <textarea class="form-control" disabled id="description" name="description" rows="10"></textarea>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-10">
        </div>
        <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
            <button type="button" class="btn btn-danger" id="btnCancel">cancel</button>
            <button type="reset" class="btn btn-primary" id="btnReset">reset</button>
            <button type="submit" class="btn btn-success" id="btnSubmit" disabled>ok</button>
        </div>
    </div>
</form>
