<?php
$id = &$this->id
?>

<form id="editOrg">
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-2 pt-0">address</legend>
            <div class="col-sm-10">
            </div>
        </div>
        <div class="row">
            <div class="col-form-label col-sm-2 pt-0">
            </div>
            <div class="col-sm-10">
                <div class="form-group row">
                    <div class="col">
                        <input type="url" class="form-control" id="url" name="url" value="" placeholder="url">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="post_office_box" name="post_office_box" value="" placeholder="post_office_box">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="street_address" name="street_address" value="" placeholder="street_address">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="extended_address" name="extended_address" value="" placeholder="extended_address">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="locality" name="locality" value="" placeholder="locality">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="region" name="region" value="" placeholder="region">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="postal_code" name="postal_code" value="" placeholder="postal_code">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="country_name" name="country_name" value="" placeholder="country_name">
                    </div>
                </div>
            </div>
        </div>
    </fieldset>

    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-2 pt-0">contact</legend>
            <div class="col-sm-10">
            </div>
        </div>
        <div class="row">
            <div class="col-form-label col-sm-2 pt-0">
            </div>
            <div class="col-sm-10">
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="role" name="role" value="" placeholder="role" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="family_name" name="family_name" value="" placeholder="family_name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="given_name" name="given_name" value="" placeholder="given_name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="additional_name" name="additional_name" value="" placeholder="additional_name">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="honorific_prefix" name="honorific_prefix" value="" placeholder="honorific_prefix">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="text" class="form-control" id="honorific_suffix" name="honorific_suffix" value="" placeholder="honorific_suffix">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="tel" class="form-control" id="tel" name="tel" value="" placeholder="tel">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col">
                        <input type="email" class="form-control" id="email" name="email" value="" placeholder="email">
                    </div>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="form-group row">
        <div class="col-10">
        </div>
        <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
            <button type="button" class="btn btn-danger" id="btnCancel">cancel</button>
            <button type="reset" class="btn btn-primary" id="btnReset">reset</button>
            <button type="submit" class="btn btn-success" id="btnSubmit">ok</button>
        </button>
    </div>
</form>
