<ul class="nav nav-tabs mb-3" id="tab-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="tab-info-tab" data-toggle="tab" href="#tab-info" role="tab" aria-controls="tab-info" aria-selected="true">Info</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab-files-tab" data-toggle="tab" href="#tab-files" role="tab" aria-controls="tab-files" aria-selected="false">
            Files <span class="badge badge-light" id="filesCount">0</span>
        </a>
    </li>
</ul>

<div class="tab-content" id="tab-tabContent">
    <div class="tab-pane active" id="tab-info" role="tabpanel" aria-labelledby="tab-info-tab">
        <form id="fetchActivity">
            <div class="form-group row">
                <div class="col-10">
                </div>
                <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                    <button type="button" class="btn btn-success my-button-activity-add">
                        new
                    </button>
                    <button type="button" class="btn btn-danger my-button-activity-remove">
                        remove
                    </button>
                </div>
            </div>

            <div class="form-group row">
                <label for="nickname" class="col-sm-2 col-form-label">employee</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="nickname" placeholder="">
                </div>
            </div>

            <div class="form-group row">
                <label for="mtime" class="col-sm-2 col-form-label">mtime</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="mtime" placeholder="">
                </div>
            </div>

            <div class="form-group row">
                <label for="org" class="col-sm-2 col-form-label" id="orgLabel"><a href="/customers/">org</a></label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="org" placeholder="">
                </div>
            </div>

            <div class="form-group row">
                <label for="description" class="col-sm-2 col-form-label">description</label>
                <div class="col-sm-10">
                    <textarea class="form-control" readonly id="description" rows="10" placeholder=""></textarea>
                </div>
            </div>
        </form>
    </div>


    <div class="tab-pane" id="tab-files" role="tabpanel" aria-labelledby="tab-files-tab">
        <div class="row">
            <div class="col-10">
            </div>
            <div class="btn-group btn-group-sm col-sm-2" role="group" aria-label="actions" >
                <button type="button" class="btn btn-success my-button-file-add">
                    new
                </button>
            </div>
        </div>
        <div class="table-responsive table-sm mt-4">
            <table class="table table-striped table-hover" id="tableFiles">
                <thead>
                    <tr>
                        <th>mtime</th>
                        <th>size</th>
                        <th>name</th>
                    </tr>
                </thead>
                <tbody>
                    <!--
                    <tr class="my-table-row-files" data-id=":N" data-href="/files/N">
                        <td>:MTIME</td>
                        <td>:SIZE</td>
                        <td>:NAME</td>
                    </tr>
                    -->
                </tbody>
            </table>
        </div>
    </div>
</div>
