<nav class="nav nav-pills flex-column" id="activityNav">
    <div class="sidebar-header">
        <h3>Activities<span class="badge badge-light" id="activityCount">0</span></h3>
    </div>

    <input class="form-control mr-sm-2 mb-2" type="search" id="activitySearch" placeholder="Filter" aria-label="activitySearch">

    <div id="activityNavLinks">
        <!--
        <a class="nav-link my-nav-link" href="/activities/N" data-href="/activities/N" data-id="N" data-name="NAME">
                :N|:NAME
        </a>
        -->
    <div>
</nav>
